-- MySQL Script generated by MySQL Workbench
-- Fri Oct  4 10:38:07 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema portfolio
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema portfolio
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `portfolio` DEFAULT CHARACTER SET utf8 ;
USE `portfolio` ;

-- -----------------------------------------------------
-- Table `portfolio`.`projects`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `portfolio`.`projects` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NOT NULL,
  `description` TEXT NOT NULL,
  `image_url` TEXT NOT NULL,
  `video_url` TEXT NULL,
  `readme_url` TEXT NULL,
  `readme_url_es` TEXT NULL,
  `url` TEXT NULL,
  `link_github_1` TEXT NULL,
  `link_github_2` TEXT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `Id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `portfolio`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `portfolio`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(255) NOT NULL,
  `username` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `role` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `Email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `Username_UNIQUE` (`username` ASC) VISIBLE,
  UNIQUE INDEX `Id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `portfolio`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `portfolio`.`categories` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `portfolio`.`technologies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `portfolio`.`technologies` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `category_id` INT UNSIGNED NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `image_url` TEXT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Technologies_Categories1_idx` (`category_id` ASC) VISIBLE,
  CONSTRAINT `fk_Technologies_Categories1`
    FOREIGN KEY (`category_id`)
    REFERENCES `portfolio`.`categories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `portfolio`.`project_technologies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `portfolio`.`project_technologies` (
  `technology_id` INT NOT NULL,
  `project_id` INT NOT NULL,
  PRIMARY KEY (`technology_id`, `project_id`),
  INDEX `fk_Technologies_has_Projects_Projects1_idx` (`project_id` ASC) VISIBLE,
  INDEX `fk_Technologies_has_Projects_Technologies_idx` (`technology_id` ASC) VISIBLE,
  CONSTRAINT `fk_Technologies_has_Projects_Technologies`
    FOREIGN KEY (`technology_id`)
    REFERENCES `portfolio`.`technologies` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Technologies_has_Projects_Projects1`
    FOREIGN KEY (`project_id`)
    REFERENCES `portfolio`.`projects` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `portfolio`.`educations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `portfolio`.`educations` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `order` INT NULL,
  `title` VARCHAR(255) NOT NULL,
  `description` TEXT NULL,
  `image_url` TEXT NULL,
  `readme_url` TEXT NULL,
  `readme_url_es` TEXT NULL,
  `institution` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `portfolio`.`education_technologies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `portfolio`.`education_technologies` (
  `education_id` INT NOT NULL,
  `technology_id` INT NOT NULL,
  PRIMARY KEY (`education_id`, `technology_id`),
  INDEX `fk_Education_has_Technologies_Technologies1_idx` (`technology_id` ASC) VISIBLE,
  INDEX `fk_Education_has_Technologies_Education1_idx` (`education_id` ASC) VISIBLE,
  CONSTRAINT `fk_Education_has_Technologies_Education1`
    FOREIGN KEY (`education_id`)
    REFERENCES `portfolio`.`educations` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Education_has_Technologies_Technologies1`
    FOREIGN KEY (`technology_id`)
    REFERENCES `portfolio`.`technologies` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `portfolio`.`technical_skills`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `portfolio`.`technical_skills` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `technology_id` INT NOT NULL,
  `proficiency` TEXT NULL,
  `order` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Skills_Technologies1_idx` (`technology_id` ASC) VISIBLE,
  CONSTRAINT `fk_Skills_Technologies1`
    FOREIGN KEY (`technology_id`)
    REFERENCES `portfolio`.`technologies` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `portfolio`.`soft_skills`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `portfolio`.`soft_skills` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NULL,
  `description` TEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `portfolio`.`soft_skills_technologies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `portfolio`.`soft_skills_technologies` (
  `technology_id` INT NOT NULL,
  `soft_skill_id` INT NOT NULL,
  PRIMARY KEY (`technology_id`, `soft_skill_id`),
  INDEX `fk_Technologies_has_SoftSkills_SoftSkills1_idx` (`soft_skill_id` ASC) VISIBLE,
  INDEX `fk_Technologies_has_SoftSkills_Technologies1_idx` (`technology_id` ASC) VISIBLE,
  CONSTRAINT `fk_Technologies_has_SoftSkills_Technologies1`
    FOREIGN KEY (`technology_id`)
    REFERENCES `portfolio`.`technologies` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Technologies_has_SoftSkills_SoftSkills1`
    FOREIGN KEY (`soft_skill_id`)
    REFERENCES `portfolio`.`soft_skills` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
